/*
 * This source file was generated by the Gradle 'init' task
 */
package numer0n;

import numer0n.factory.service.GameManagerFactory;
import numer0n.service.GameManager;

public class App {

    public static void main(String[] args) {
        GameManager gameManager = GameManagerFactory.create();

        // 理想的なつくりではないかもしれない
        // ゲームを開始
        gameManager.start();
    }
}
